server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spirngb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis: #连接远程redis
    host: 192.168.95.129
  rabbitmq: #rabbitmq
    host: 192.168.95.129
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo