server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.95.129:9300
  jackson:
    default-property-inclusion: non_null #页面显示属性不包含null的字段
  rabbitmq:
      host: 192.168.95.129 #rabbitmq 端口默认5672
      virtual-host: /leyou #虚拟主机
      username: leyou
      password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10 #拉取微服务
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #无效时间